export default {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
  LOAD_PIZZAS: 'LOAD_PIZZAS',
  LOAD_PIZZAS_ERROR: 'LOAD_DRINKS_ERROR',
  LOAD_DRINKS: 'LOAD_DRINKS',
  LOAD_DRINKS_ERROR: 'LOAD_DRINKS_ERROR',

  LOAD_PIZZA: 'LOAD_PIZZA',
  LOAD_PIZZA_ERROR: 'LOAD_PIZZA_ERROR',

  LOGIN: 'LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  LOGOUT_ERROR: 'LOGOUT_ERROR',

  ADD_PRODUCTS_TO_CART: 'ADD_PRODUCTS_TO_CART',
  ADD_PRODUCTS_TO_CART_ERROR: 'ADD_PRODUCTS_TO_CART_ERROR',
  LOAD_CART_PRODUCT: 'LOAD_CART_PRODUCT',
  LOAD_CART_PRODUCT_ERROR: 'LOAD_CART_PRODUCT_ERROR',
  DELETE_CART_PRODUCT: 'DELETE_CART_PRODUCT',
  DELETE_CART_PRODUCT_ERROR: 'DELETE_CART_PRODUCT_ERROR',
  LOAD_PRODUCT_ERROR: 'LOAD_PRODUCT_ERROR',
  DECREASE_PRODUCT_QUANTITY: 'DECREASE_PRODUCT_QUANTITY',
  DECREASE_PRODUCT_QUANTITY_ERROR: 'DECREASE_PRODUCT_QUANTITY_ERROR',

  ADD_COSTUMER: 'ADD_COSTUMER',
  ADD_COSTUMER_ERROR: 'ADD_COSTUMER_ERROR',

  LOAD_EMPLOYEE: 'LOAD_EMPLOYEE',
  LOAD_EMPLOYEE_ERROR: 'LOAD_EMPLOYEE_ERROR',

  GET_PAYMENT: 'GET_PAYMENT',
  GET_PAYMENT_ERROR: 'GET_PAYMENT_ERROR'
};
